### ISSUE TITLE
tSNE/PCA visualization for embedding space with class anchors

### ISSUE THREAD

**Issue by divyagupta25** [fywalter/simptc#1]
Hi, 

Thank you for sharing your work!
Could you please point me to the code for reproducing the visualizations in the paper? 

Thanks in advance!

**Comment by fywalter** [comment]
Hi,

Just added the code for visualizing the embedding spaces. Please check the repo:)

**Comment by divyagupta25** [comment]
Thank you so much! :D

**Comment by divyagupta25** [comment]
@fywalter Could you please share the Hugging Face model name of the T5-3B model mentioned in the paper? I tried "sentence-transformers/sentence-t5-base", "t5-base" and "t5-large" but getting poorer results. 

Update: Found https://huggingface.co/t5-3b

Update 2: Poorer embedding space visualisation and results with T5-3B as well (on custom dataset). Yet to try on public.

Thank you!

**Comment by fywalter** [comment]
We used t5-3b (https://huggingface.co/t5-3b) for our experiments.
> Poorer embedding space visualization and results with T5-3B as well

By poorer, do you mean compared with SimCSE or RoBERTa embeddings? If that's the case, it would be interesting to find out why (especially if it is poorer than RoBERTa large embeddings).

**Comment by divyagupta25** [comment]
Compared with SimCSE. 
Added more details in the [new issue ](https://github.com/fywalter/simptc/issues/2). Please have a look. 

Thank you!
